### ISSUE TITLE
widget_get_png_from_file

### ISSUE THREAD

**Issue by sjaehn** [brummer10/libxputty#9]
Hi Hermann,

finally I found some time (which I don't have got ;-)) to take a closer look to libxputty. Some smart solutions and it looks really efficient for low complexity UIs. And I'm going to use it in two of my next tutorial videos (in April 2023).

However, I initially struggled to load a .png image file (I mean the file, not converted to .c and hard compiled) and to visualize it. You created `widget_get_png (Widget_t *w,  const unsigned char* name)`, which looks like doing this job. However, it expects a data stream for `name` and not the filename. A bit confusing ;-). And there are a lot of similar methods in xpngloader.h, but all expect img data for `name` instead of a filename.

On the other hand, there is a `widget_get_svg (Widget_t *w, const char* name)` in xsvgloader.h doing exactly what I expect. `name` is the filename there.

Therefore my feature request: Add a png loading function from a .png file. Like `widget_get_png_from_file  (Widget_t *w, const char* name)` to not break the API. And it would be nice to rename the parameter `name` for the png stream-accepting `widget_get...` functions to data or stream or ... . Just for more clearness.

Viele Grüße
Sven

**Comment by brummer10** [comment]
Hi Sven
Nice to hear you like the way I've done libxputty, and that you'll go to promote it a bit. 
To `widget_get_svg`, this one expected a base64 encoded char (thus could be embedded in a binary), not a svg file.
To load from file there is the `widget_get_svg_from_file` call, there the parameter name is `filename`.

Sure, I could add the same to PNG loader. Currently there is such a functionality in xfile-dialoge.c `show_preview`
It's fairly easy to get a PNG loaded from file directly with cairo, while to load a SVG it needs some trickery. That's why I only added that for SVG files, not for PNG. 

gruß
hermann

**Comment by sjaehn** [comment]
You are right, `*_svg_from_file` is the right one.  And yes, loading a png from a file into something like a surface like `Widget_t::image` is cheap and can be done in two lines of code. But you can get it even cheaper. Without touching cairo by the xputty user. It's not a "must have", only a "nice to have". Maybe think about it ;-).

**Comment by brummer10** [comment]
Yes, I'll add that as it makes the API more comparative to the SVG one. Just give me some day's.

**Comment by brummer10** [comment]
So it's done. Thanks for the suggestion.

**Comment by sjaehn** [comment]
Tested. It works. And I re-recorded a part of my tutorial video to include this function. Thanks a lot.

**Comment by sjaehn** [comment]
FYI, the code for the tutorial I mentioned and the first out of two videos is online since last Friday: https://github.com/sjaehn/lv2tutorial . The second one is scheduled for this Friday.

**Comment by brummer10** [comment]
Nice, many thanks for promoting libxputty this way.
